### ISSUE TITLE
Some examples?

### ISSUE THREAD

**Issue by raphaelchinchilla** [GrattonToint/S2MPJ#1]
Dear all,

I am very excited to have found this work you all have done. I have been waiting for years for someone to do something similar to this.

Do you think it would be possible to write some basic examples of how to use the functions in Matlab, Julia and Python? I am talking really basic, something like using gradient descent to solve the Rosenbrock problem (with fixed step length). 

You all describe a bit how to use it in the article, but it is very abstract and I think some examples would make it easier.

**Comment by phtoint** [comment]
Have yu checked the xample in the paper (s2pmj.pdf) ?

**Comment by phtoint** [comment]
Oups, sorry for the typos! If you think the example in the paper are too abstrct, we may think of something along the lines you suggest.

**Comment by raphaelchinchilla** [comment]
I ended up figuring it out, but it took me a while, so a full tutorial might help?

I might end up writing a toy example to get a better understanding of how to use it, and I can make a PR
